version: '3.8'

services:
  enrolment-management-db:
    container_name: enrolment-management-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: frank
      MYSQL_DATABASE: spring_mvc
    ports:
      - 3306:3306

  enrolment-management-web:
    container_name: enrolment-management-web
    image: franktranvantu/enrolment-management:1.0.0
    ports:
    - 8080:8080
    depends_on:
      - enrolment-management-db