server:
  servlet:
    context-path: /

spring:
  profiles:
    active: heroku
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: /WEB-INF/static

  mail:
    host: smtp.gmail.com
    username: franktranvantu@gmail.com
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true