spring:
  profiles:
    active: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: /WEB-INF/static

  mail:
    host: smtp.gmail.com
    username: java.mail.0905@gmail.com
    password: hjgccqdqohovxott
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true