spring:
  profiles:
    active: heroku
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: /WEB-INF/static
  mail:
    host: smtp.gmail.com
    username: java.mail.0905@gmail.com
    password: hjgccqdqohovxott
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
sentry:
  dsn: https://d9548dc031ff4309a70df305ae3cd9df@o722716.ingest.sentry.io/5781749
  exception-resolver-order: 2147483647